# GradMemGPT on SQuAD - default configuration

model:
  base_model: pythia

training:
  per_device_batch_size: 2
  total_batch_size: 2
  learning_rate: 1.0e-4
  max_steps: 200000
  eval_steps: 500
  logging_steps: 500
  warmup_steps: 5000
  early_stopping_patience: 500
  use_gradient_checkpointing: false
  seed: 142

dataset:
  data_name: "squad"
  data_path: "./data/squad"

gradmem:
  n_mem_tokens: 2
  n_ctrl_tokens: 0
  K: 2
  inner_lr: 0.25
  inner_clip_value: null
  inner_clip_norm: null
  use_adam: false
  grad_mode: "second"
  use_mem_proj: true
  mem_proj_mode: "proj"
  use_write_head: true
  add_inner_loss_to_outer: false

# Hopfield-like external memory configuration
hopfield:
  use_hopfield_memory: true
  hopfield_n_segments: 1