# GPT2 on phonebook - default configuration

model:
  pretrained_model: gpt2

training:
  per_device_batch_size: 64
  total_batch_size: 256
  learning_rate: 3.0e-4
  max_steps: 200000
  eval_steps: 500
  logging_steps: 500
  warmup_steps: 10000
  early_stopping_patience: 500
  seed: 142

dataset:
  data_name: "booydar/phonebook_N2"
  # data_path: auto-computed from data_name
  tokenizer_path: "./tokenizers/kv_alphabet_62/"